Jenkins:
  systemMessage: "Jenkins managed by Configuration as Code"
  numExecutors: 1
  nodes:
    - permanent:
        labelString: "mac_mini"
        mode: NORMAL
        name: "buildmachine_macos_ios"
        numExecutors: 1
        remoteFS: "/Users/jenkins"
        launcher:
          SSHLauncher:
            host: "192.168.2.220"
            port: 22
            credentialsId: jenkins_slave_key
            launchTimeoutSeconds: 20
            maxNumRetries: 2
            retryWaitTime: 15
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false
    - permanent:
        labelString: "mac_ubuntu"
        mode: NORMAL
        name: "buildmachine_linux_android"
        numExecutors: 1
        remoteFS: "/home/jenkins"
        launcher:
          SSHLauncher:
            host: "192.168.2.221"
            port: 2030
            credentialsId: jenkins_slave_key
            launchTimeoutSeconds: 20
            maxNumRetries: 2
            retryWaitTime: 15
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false
    - permanent:
        labelString: "mac_wine"
        mode: NORMAL
        name: "buildmachine_windows"
        numExecutors: 1
        remoteFS: "/home/jenkins"
        launcher:
          SSHLauncher:
            host: "192.168.2.221"
            port: 2040
            credentialsId: jenkins_slave_key
            launchTimeoutSeconds: 20
            maxNumRetries: 2
            retryWaitTime: 15
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false
credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: SYSTEM
              id: jenkins_slave_key
              username: jenkins
              passphrase: ""
              description: "SSH private key file for connecting the Mac Mini build slave."
              privateKeySource:
                directEntry:
                  privateKey: ${jenkins_slave_key}
jobs:
  - script: >
      pipelineJob('helloworld') {
          definition {
              cpsScm {
                  scm {
                      git {
                          remote {
                              url('https://github.com/redturtlepower/demo_qmake_hello_world.git')
                          }
                          branches('master','develop')
                          scriptPath('Jenkinsfile.v4')
                          extensions { }
                      }
                  }
              }
          }
      }
