version: '3.1'
services:
  master:
    build: src
    ports:
    - "8080:8080"
    volumes:
    - ./jenkins_home:/var/jenkins_home
    restart: always
    secrets:
      - jenkins_slave_key
secrets:
  jenkins_slave_key:
    file: ~/.ssh/jenkins_slave
